### ISSUE TITLE
python manage.py celery worker?

### ISSUE THREAD

**Issue by giohappy** [olivierdalang/SPCgeonode#1]
From your celery container I see you're using a command that I remember coming from djcelery's  management commands: https://github.com/olivierdalang/SPCgeonode/blob/39139b6016f11767691885aad75f05ddc56c2c27/docker-compose.yml#L44

Is it from djcelery or from some other module? In case it's djcelery, isn't it deprecated for Celery 4.1?

**Comment by olivierdalang** [comment]
It comes from django-celery. I think you're right saying it is deprecated for celery 4 (but so far SPCGeonode uses Geonode 2.6.3 which uses celery 3).

**Comment by giohappy** [comment]
ok thx
