### ISSUE TITLE
SPCgeonode centOS Installation

### ISSUE THREAD

**Issue by indeOWS** [olivierdalang/SPCgeonode#2]
Dear Olivier Dalang,

I am working on SPCgeonode in a CentOS7 VM. I got docker-ce_17.12.1~ce and docker-compose@1.19.0 installed according to the prerequisites. While running the command (docker-compose -f docker-compose.yml up -d --build), the installation process got the following error: 

_Connecting to downloads.rclone.org (5.153.250.7:443)
ssl_client: downloads.rclone.org: TLS connect failed
wget: error getting response: Connection reset by peer
ERROR: Service 'rclone' failed to build: The command '/bin/sh -c wget https://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip' returned a non-zero code: 1_

One thing I noticed is that running the command line  /bin/sh -c "wget https://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip" works if wget is set between quotes on the terminal. I commented the lines bellow in the Dockerfile, and I did all the commands (under RUN) via terminal, but the installation is not successful and the docker-compose logs -f gets printing errors and never stops.  
# 3. Install Rclone
#RUN wget https://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip
#RUN unzip /rclone-v1.39-linux-amd64.zip
#RUN rm /rclone-v1.39-linux-amd64.zip
#RUN mv /rclone-v1.39-linux-amd64/rclone /usr/bin

Could you please give a hint in what this issue is related to? 

Thank you for your time in advance.

**Comment by t-book** [comment]
Dear Julierme, 
this made me sleeples. This is how I got it running:
In `_service_rclone/Dockerfile` use these lines 

```
RUN apk update && apk add --no-cache unzip && apk add wget
RUN wget --no-check-certificate http://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip
```

instead of:

```
RUN wget https://downloads.rclone.org/v1.40/rclone-v1.40-linux-amd64.zip`
```

This makes it run but it would be intersting to know what making it fail under centos7 host. 
Let´s wait what Oliver thinks.

cheers,

toni

**Comment by olivierdalang** [comment]
Hey ! Sorry for that...

Actually the issue also happens in Travis so doesn't seem specific to your system... (unfortunately I didn't spot it as tests were already failing because of me trying to add integration tests)

I'm investigating...

By the way, which branch are you using ? If it was `release`, I just pushed some fixes, it should be trying to download rclone v1.40 but your error message mentions v1.39 (but this probably won't change your problem)

**Comment by olivierdalang** [comment]
Ok found https://github.com/gliderlabs/docker-alpine/issues/423 that seems to indicate some issue with alpine.

In travis it does the job, @juliermegeotube can you confirm this fixes it on your setup too ?

**Comment by indeOWS** [comment]
Dear @t-book and @olivierdalang 
I finally got to test both solutions. Thank you both for such a great job.
Yes, @t-book 'solution worked by doing the following:
FROM alpine:3.6
<**Install Rclone**>
RUN apk add --no-cache openssl
<**Install Rclone**>
RUN apk update && apk add --no-cache unzip && apk add wget
RUN wget --no-check-certificate http://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip
@olivierdalang,  yes, I am using the release branch and  and your solution worked by doing the following:
< **Install deps**>
RUN apk add --no-cache libressl ca-certificates
<**instead of using openssl**>

I have no words to thank you both for presenting a solution.
Wonderful job!!!!
Kind regards

**Comment by indeOWS** [comment]
Dear @t-book <https://github.com/t-book> and @olivierdalang
<https://github.com/olivierdalang>
I finally got to test both solutions. Thank you both for such a great job.
Yes, @t-book <https://github.com/t-book> 'solution worked by doing the
following:
FROM alpine:3.6
<*Install Rclone*>
RUN apk add --no-cache openssl
<*Install Rclone*>
RUN apk update && apk add --no-cache unzip && apk add wget
RUN wget --no-check-certificate
http://downloads.rclone.org/v1.39/rclone-v1.39-linux-amd64.zip
@olivierdalang <https://github.com/olivierdalang>, yes, I am using the
release branch and and your solution worked by doing the following:
< *Install deps*>
RUN apk add --no-cache libressl ca-certificates
<*instead of using openssl*>

I have no words to thank you both for presenting a solution.
Wonderful job!!!!
Kind regards

**Comment by t-book** [comment]
You´re welocome Julierme, 

the solution Olivier posted is the cleaner one and the way to go!

+1 Oliver ;)

cheers,

toni
